M48
; DRILL file {KiCad 7.0.5} date Sun Jun 18 14:53:13 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-18T14:53:13+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X1.4159Y-1.2402
T2
X1.2556Y-1.0011
X1.8124Y-1.5579
T0
M30
