M48
; DRILL file {KiCad 7.0.6-rc1-25-gf974c8259e} date Wed Jun 21 18:20:30 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-21T18:20:30+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-rc1-25-gf974c8259e
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X1.4227Y-1.3352
T2
X1.2556Y-1.0011
X1.8124Y-1.5579
T0
M30
